django-library/p_library/library/urls.py
from django.urls import path, include
from . import views
from .views import AuthorEdit, AuthorList, FriendEdit, FriendList

app_name = 'library'
urlpatterns = [
    path('', views.index, name='home'), # путь домашней страницы, использует шаблон index.html
    path('library/', views.library, name='library'), # путь библиотеки, шаблон library.html
    path('book_increment/', views.book_increment),    
    path('book_decrement/', views.book_decrement), # пути форм для добавления/изъятия книг из библиотеки, шаблоны book_increment.html. book_decrement.html соответсвенно
    path('redactions/', views.redactions, name='redactions'), # путь издательств, шаблон redactions.html
    path('authors/create', AuthorEdit.as_view(), name='author_create'), # путь формы создания автора, шаблон author_edit.html
    path('authors', AuthorList.as_view(), name='author_list'), # путь списка авторов, шаблон authors_list.html
    path('authors/create_many', views.author_create_many, name='author_create_many'),
    path('authors/books_authors_create_many', views.books_authors_create_many, name='books_authors_create_many'), # два пути из модуля, могут быть игнорированы
    path('friends', FriendList.as_view(), name='friends'), # путь списка друзей, шаблон friends.html
    path('friends/create', FriendEdit.as_view(), name='friend_create'), # путь формы создания друзей, шаблон friends_create.html
    path('lend/<int:book_id>', views.lend_book, name='lend'), # путь формы одалживания книги, шаблон lend.html
    path('borrowers', views.borrowers, name='borrowers'), # путь списка должников, путь borrowers.html
]

django-library/p_library/library_auth/urls.py
from library_auth.views import index
from django.urls import path, reverse_lazy, include
from allauth.account.views import login, logout
  
app_name = 'library_auth'  
urlpatterns = [  
    path('', include('library.urls', namespace='library')),  
	path('login/', login, name='login'),  
	path('logout/', logout, name='logout'),
]

django-library/p_library/p_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls), # собственно, админ панель
    path('accounts/', include('allauth.urls')),
    path('', include('library_auth.urls')),
    path('', include('library.urls')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-library/p_library/library/models.py
from django.db import models


class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    def __str__(self):
    	return self.full_name


class Redaction(models.Model):
    name = models.TextField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.PositiveIntegerField(default=1)
    price = models.DecimalField(default=0, max_digits=12, decimal_places=2)
    redaction = models.ForeignKey(Redaction, default=None, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='covers/', null=True)

    def __str__(self):
    	return self.title


class Friend(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    borrowed_books = models.ManyToManyField(Book, related_name='book', blank=True)

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

django-library/p_library/library/forms.py
from django import forms
from library.models import Author, Book, Friend


# Модель создания нового автора
class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',            # Добавляем бутстраповский класс для стайлинга формы
            'placeholder': 'e.g. John Doe',     # Добавляем placeholder для конкретики
        }
    ))
    birth_year = forms.IntegerField(widget=forms.NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'e.g. 1954',
        }
    ))
    country = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'e.g. EN',
        }
    ))

    class Meta:
        model = Author
        fields = '__all__'

# Форма создания новой книги
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

# Форма создания нового друга. Работала бы в реальной жизни, эхх...
class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = '__all__'

django-library/p_library/library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from library.models import Book, Author, Redaction, Friend
from library.forms import AuthorForm, BookForm, FriendForm
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

import json


# Отображение стартовой страницы, нулевой функционал
def index(request):
    return render(request, 'index.html')

# Отображение списка книг из библиотеки
def library(request):
    template = loader.get_template('library.html')
    books = Book.objects.all()
    biblio_data = {
        "title": "my personal library",
        "books": books,
    }
    return HttpResponse(template.render(biblio_data, request))

# Увеличение количества определенной книги
def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            book.copy_count += 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

# Уменьшение количества определенной книги
def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

# Отображение списка издательств
def redactions(request):
    template = loader.get_template('redactions.html')
    books = Book.objects.all()
    redactions = Redaction.objects.all()
    data = {
        "redactions": redactions,
        "books": books,
    }

    return HttpResponse(template.render(data, request))

# Отображение списка авторов
class AuthorList(ListView):
    model = Author
    template_name = "authors_list.html"

# Создание нового автора с помощью формы
class AuthorEdit(SuccessMessageMixin, CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy("author_list")
    success_message = "Author was created successfully"
    template_name = "authors_edit.html"

# Отображение списка друзей
class FriendList(ListView):
    model = Friend
    template_name = "friends.html"

# Создание нового друга с помощью формы
class FriendEdit(CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy("friends")
    template_name = "friends_create.html"

# Создание нескольких авторов с помощью formset
def author_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    if request.method == 'POST':

        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')

        if author_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            return HttpResponseRedirect(reverse_lazy('author_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
    
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

# Создание нескольких книг и авторов с помощью formset
def books_authors_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BookFormSet = formset_factory(BookForm, extra=2)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if author_formset.is_valid() and book_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            for book_form in book_formset:
                book_form.save()
            return HttpResponseRedirect(reverse_lazy('author_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
        book_formset = BookFormSet(prefix='books')
    return render(request, 'manage_books_authors.html', {'author_formset': author_formset, 'book_formset': book_formset})

# Выдача книги в долг
def lend_book(request, book_id):
    # Находим нужную книгу и достаем список друзей
    book = Book.objects.get(id__exact=book_id)
    friends = Friend.objects.all()

    if request.method == 'POST':
        friend_id = request.POST.get('id')  # Получаем id нужного друга
        friend = friends.get(id=friend_id)  # и находим его в списке всех друзей

        # Проверка на наличие запрашиваемой книги у друга
        if book in friend.borrowed_books.all():
            messages.error(request, 'This friend already has this book.')
            return HttpResponseRedirect(reverse_lazy('borrowers'))

        friend.borrowed_books.add(book)
        book.copy_count -= 1
        book.save()
        return HttpResponseRedirect(reverse_lazy('borrowers'))

    return render(request, 'lend.html', {'book': book, 'friends': friends})

# Отображение списка должников
def borrowers(request):
    borrowers = Friend.objects.exclude(borrowed_books__isnull=True).all() # Фильтруем запрос, исключая друзей, которые не брали книг вовсе
    return render(request, 'borrowers.html', {'borrowers': borrowers} )

django-library/p_library/library/templates/authors_edit.html
{% extends 'index.html' %}

{% block extracss %}

{% load static %}
<link rel='stylesheet' href={% static 'library/author_edit.css' %}>

{% endblock %}

{% block content %}

<div class='container'>
  <section class='form-section'>
    <p class="h3">To add an author, please enter valid information into the fields below</p><br>
      <form class="author-edit" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group row">
            <label class='col-sm-2 col-form-label'>
              {{ field.label }}
            </label>
            <div class="col-sm-10">
              {{ field }}
            </div>
          </div>
        {% endfor%}

        <input type="submit" class="btn btn-primary" value="Save">
      </form>
  </section>
</div>

{% endblock %}

django-library/p_library/library/templates/authors_list.html
{% extends 'index.html' %}


{% block content %}

<div class='container'>
  {% if messages %}
    <div class="alert alert-success" role="alert">
      <ul class="messages">
      {% for message in messages %}
        <li> {{ message }} </li>
      {% endfor %}
      </ul>
    </div>
  {% endif %}

  <ul class="list-group">
    {% for author in object_list %}
      <li class="list-group-item">
        <span class="badge badge-secondary text-wrap" style="width: 2rem;">{{ author.country }}</span> 
        {{ author.full_name }}
      </li>
    {% endfor %}
  </ul>
  <br>
  <a class="btn btn-primary" href="/authors/create" role="button" style="margin-left:20px;">Create an author</a>
  <a class="btn btn-primary" href="/authors/create_many" role="button" style="margin-left:20px;">Create multiple authors</a>
  <a class="btn btn-primary" href="/authors/books_authors_create_many" role="button" style="margin-left:20px;">Create multiple authors and books</a>
</div>
{% endblock %}

django-library/p_library/library/templates/borrowers.html
{% extends 'index.html' %}

{% block content %}

{% if messages %}
<ul class="messages alert alert-warning" role="alert">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

Current borrowers:
<ul>
    {% for friend in borrowers %}

    <li>{{ friend }} currently has:
      <ul class='list-group'>
        {% for book in friend.borrowed_books.all %}
          <li class='list=group-item'>{{ book }}</li>
        {% endfor %}
      </ul>
    </li>

    {% endfor %}
</ul>

{% endblock %}

django-library/p_library/library/templates/friends.html
{% extends 'index.html' %}


{% block content %}

<ul>
  {% for friend in object_list %}
    <li>{{ friend.last_name }} {{ friend.first_name }}</li>
  {% endfor %}
</ul>

<a class="btn btn-primary" href="/friends/create" role="button" style="margin-left:20px;">Create a friend</a>

{% endblock %}

django-library/p_library/library/templates/friends_create.html
{% extends 'index.html' %}
{% block content %}
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

django-library/p_library/library/templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <link rel='stylesheet' href={% static 'library/bootstrap.css' %}>
  <link rel='stylesheet' href={% static 'library/style.css' %}>
  {% block extracss %}{% endblock %}
  <title>Lib</title>

</head>

<header>
  <nav class="navbar navbar-dark bg-dark">
    <ul>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'library:library' %}">Library</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'library:redactions' %}">Redactions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'library:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'library:author_list' %}">Authors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'library:borrowers' %}">Borrowers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'library:friends' %}">Friends</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" 
        {% if user.is_authenticated %}
          href="{% url 'library_auth:logout' %}">Logout
        {% else %}
          href="{% url 'library_auth:login' %}">Login
        {% endif %}
        </a>
      </li>
    </ul>
  </nav>
</header>

<body>

  {% block content %}
  <div class="jumbotron">
    <h1 class="display-4">
    {% if user.is_authenticated %}
    Hello, {{ user }}! 
    {% endif %}
    Welcome to my Personal Library</h1>
    <p class="lead">This is a collection of my personal preference built with tons of bootstrap copypastes</p>
    <hr class="my-4">
    <p>Please use the navbar above to navigate through this humble website</p>
  </div>

  <div class='container'>

  </div>
  {% endblock %}

</body>

</html>

django-library/p_library/library/templates/lend.html
{% extends 'index.html' %}

{% block content %}

<p>You want to lend a book called {{ book.title }} by {{ book.author }}. There are {{ book.copy_count }} available copies. Select a borrower.</p>

{% for friend in friends %}
  <form method='post'>
    {% csrf_token %}
    {{ friend }}
    <input type='hidden' name='id' value={{ friend.id }} />
    <input type='submit' />
  </form>
{% endfor %}

{% endblock %}

django-library/p_library/library/templates/library.html
{% extends "index.html" %}

{% block extracss %}

{% load static %}
<link rel='stylesheet' href={% static 'library/library.css' %}>

{% endblock %}

{% block content %}

<div class="container-fluid">
  <p style="margin:auto; width:50%;text-align:center;padding:15px;font-size:18px;">
    Welcome to {{ title }}.<br>
    There are currently {{ books|length }} books in this collection. Feel free to explore.
  </p>

  <div class="row books">
    {% for book in books %}
      <div class="card col col-md-3" style="width: 18rem;">
        <img src="../media/{{ book.cover }}" class="card-img-top" alt="..." height="400px" width="auto">
        <div class="card-body">
          <div class="title-wrapper">
            <h5 class="card-title">{{ book.title }}, {{ book.year_release }}</h5>
              <p><em>by {{ book.author }}</em></p>
              <p><small>Published by {{ book.redaction }}</small></p>
          </div>  {# class "title-wrapper" #}
          <p class="card-text">{{ book.description }}</p>
          <div class="panel-wrapper">
            {% if book.copy_count > 0 %}
              <p class="alert alert-info" role="alert">There are currently {{ book.copy_count }} books available</p>
            {% else %}
              <p class="alert alert-warning" role="alert">There are no book available right now</p>
            {% endif %}
            <div class="row">
              <form action="/library/book_increment/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}" />
                <input class="btn btn-outline-primary" type="submit" value="Add" />
              </form>
              <form action="/library/book_decrement/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}" />
                <input class="btn btn-outline-primary" type="submit" value="Remove" />
              </form>
              <form action="/lend/{{ book.id }}">
                <input class="btn btn-outline-primary" type="submit" {% if book.copy_count == 0 %}disabled{% endif %} value="Lend" />
             </form>
            </div>  {# class "row" #}
          </div>  {# class "panel-wrapper" #}
        </div>  {# class "card-body" #}
      </div>  {# class "card col col-md-3" #}
    {% endfor %}

  </div>  {# class "row books" #}
</div>  {# class "container-fluid" #}

{% endblock %}

django-library/p_library/library/templates/manage_authors.html
{% extends 'index.html '%}

{% block content %}

<form method='post'>
  {% csrf_token %}
  
  {% for form in author_formset %}
    {{ form.as_p }}
    <br>    
    {{ author_formset.management_form }}
  {% endfor %}
  
  <input type='submit' value='Save' />
</form>

{% endblock %}

django-library/p_library/library/templates/manage_books_authors.html
{% extends 'index.html' %}

{% block content %}

<form method='post'>
  {% csrf_token %}
  <p class='h3' style="padding: 15px 0px;">Add authors below</p>
  
  {% for form in author_formset %}
    {{ form.as_p }}
    <br>
  {% endfor %}
  
  {{ author_formset.management_form }}
  <p class='h3' style="padding: 15px 0px;">Add books below</p>
  
  {% for form in book_formset %}
    {{ form.as_p }}
    <br>
  {% endfor %}
  
  {{ book_formset.management_form }}
  <input type='submit' value='Save' />
</form>
{% endblock %}

django-library/p_library/library/templates/redactions.html
{% extends "index.html" %}

{% block content %}

<div class="container-fluid">
  <ul>
  {% for red in redactions %}
    <li class="list-group-item">
      <span style="font-size:18px;">"{{ red.name }}" with {{ red.book_set.count }} items</span>
      <ul class="list-group">
    
        {% for book in books %}
          {% if book.redaction.id == red.id %}
            <li class="list-group-item">
              {{ book.title }} by {{ book.author }}
            </li>
          {% endif %}
        {% endfor %}
      </li>
    </ul>
  {% endfor %}
  </ul>
</div>

{% endblock %}