gu-festival/festival/urls.py
from django.urls import path
from .views import *

app_name = 'festival'
urlpatterns = [
    path('', index, name='home'),
    path('schedule/', ArenaList.as_view(), name='schedule'),
    path('request/', BandRequestPost.as_view(), name='band-request'),
    path('request/status/', BandRequestStatus.as_view(), name='request-status'),
    path('requests', BandRequestList.as_view(), name='requests'),
    # path('vote/', band_request_update, name='vote'),
    # path('requests/<int:pk>', BandRequestDetail.as_view(), name='request-detail'),
    path('requests/<int:pk>', CensorVoteCreate.as_view(), name='vote'),
    path('request/<int:pk>/<int:decision>', BandRequestUpdate.as_view(), name='decision'),
]

gu-festival/glukhie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('festival.urls')),
    path('account/', include('user_management.urls')),
    path('account/', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

gu-festival/user_management/urls.py
from allauth.account.views import login, logout
from django.urls import path
from .views import CreateUserProfile


app_name = 'user_management'

urlpatterns = [
    path('profile/', CreateUserProfile.as_view(), name='profile'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

gu-festival/festival/models.py
from django.db import models
from user_management.models import UserProfile


# Arena Model, complete
class Arena(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name
    

# ArenaTimeSlot model, complete
class ArenaTimeSlot(models.Model):
    NOON = 1
    DUSK = 2
    EVENING = 3

    TIME_CHOICES = [
        (NOON, "День"),
        (DUSK, "Ранний вечер"),
        (EVENING, "Поздний вечер"),
    ]
    
    arena = models.ForeignKey(Arena, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.IntegerField(choices=TIME_CHOICES, default=None)
    capacity = models.SmallIntegerField(default=0)
    reserved = models.SmallIntegerField(default=0)

    def __str__(self):
        return f"{self.arena} - {self.get_time_display()} - {self.date}"
    

# Band request model, complete
class BandRequest(models.Model):
    PASSED = 1
    REJECTED = 2
    IN_PROGRESS = 3

    STATUS = [
        (PASSED, 'Passed'),
        (REJECTED, 'Rejected'),
        (IN_PROGRESS, 'In progress'),
    ]

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    band_name = models.CharField(max_length=255)
    request_text = models.TextField()
    timeslot = models.ForeignKey(ArenaTimeSlot, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=IN_PROGRESS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Request by {self.band_name}"
    

# Censor vote model, complete
class CensorVote(models.Model):
    PASS = 1
    REJECT = 2

    VOTES = [
        (PASS, 'Pass'),
        (REJECT, 'Reject'),
        (None, 'None'),
    ]

    censor = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    band_request = models.ForeignKey(BandRequest, on_delete=models.CASCADE)
    vote = models.IntegerField(choices=VOTES, default=None)

gu-festival/festival/forms.py
from django import forms
from .models import BandRequest, CensorVote


class BandRequestForm(forms.ModelForm):
    class Meta:
        model = BandRequest
        fields = ('band_name', 'request_text', 'timeslot')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['band_name'].widget.attrs.update({'class':'form-control'})
        self.fields['request_text'].widget.attrs.update({'class':'form-control'})
        self.fields['timeslot'].widget.attrs.update({'class':'form-control'})


class CensorVoteForm(forms.ModelForm):

    class Meta(object):
        model = CensorVote
        fields = '__all__'
        widgets = {
            'band_request': forms.HiddenInput(),
            'censor': forms.HiddenInput(),
            'vote': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

gu-festival/festival/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Arena, ArenaTimeSlot
from django.views.generic import ListView, CreateView, DetailView, UpdateView, CreateView
from .forms import BandRequestForm, CensorVoteForm
from .models import BandRequest, CensorVote
from user_management.models import UserProfile
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from .mixins import GroupRequiredMixin
from django.views.generic import View
import datetime

# Homepage view, no functionality
def index(request):
    return render(request, 'festival/home.html')
    
# List all the Arenas and available ArenaTimeSlots
class ArenaList(ListView):
    context_object_name = 'arena_list'

    def get_queryset(self):
        return Arena.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ArenaList, self).get_context_data(**kwargs)
        context['arena_timeslot_first'] = ArenaTimeSlot.objects.filter(date=datetime.date(2020,1,30))
        context['arena_timeslot_second'] = ArenaTimeSlot.objects.filter(date=datetime.date(2020,1,31))
        context['bands'] = BandRequest.objects.filter(status=1)
        print(context['arena_timeslot_first'])
        print(context['arena_timeslot_second'])
        return context

# Handling the form for new band requests
class BandRequestPost(SuccessMessageMixin, GroupRequiredMixin, CreateView):

    group_required= ['admin', 'Censor', 'Musician']

    model = BandRequest
    form_class = BandRequestForm
    success_url = reverse_lazy('festival:home')
    template_name = 'festival/band_request.html'

    def form_valid(self, form):
        user = UserProfile.objects.get(user=self.request.user)
        form.instance.user = user
        return super(BandRequestPost, self).form_valid(form)

# Showing the status of the particular BandRequest (for Musicians)
class BandRequestStatus(GroupRequiredMixin, ListView):

    group_required = ['admin', 'Censor', 'Musician']

    model = BandRequest
    template_name = 'festival/user_request.html'
    context_object_name = 'bandrequest'
    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.get(user=self.request.user)
            return BandRequest.objects.filter(user=profile)
        else:
            return BandRequest.objects.none()

# Listing of all pending, approved and rejected BandRequests (for Censors)
class BandRequestList(GroupRequiredMixin, ListView):

    group_required = ['admin', 'Censor']

    model = BandRequest
    context_object_name = 'bandrequests'
    template_name = 'festival/requests.html'

    def get_context_data(self, *args, **kwargs):
        context = super(BandRequestList, self).get_context_data(*args, **kwargs)

        band_votes = {}

        # Very ugly method for getting the dictionary of BandRequest objects and calculated value of censor votes
        # NEEDS REVIEWING
        for i in BandRequest.objects.all():
            votes = 0
            for j in CensorVote.objects.all():
                if j.band_request == i:
                    if j.vote == 1:
                        votes += 1
                    elif j.vote == 2:
                        votes -= 2
            band_votes[i] = votes

        context['votes'] = band_votes
        print(context['votes'])
        return context
 
# Giving a censor an opportunity to accept or reject the pending request
class CensorVoteCreate(GroupRequiredMixin, CreateView):

    group_required = ['admin', 'Censor']

    model = CensorVote
    template_name = 'festival/vote.html'
    form_class = CensorVoteForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('festival:home')
    
    def get_initial(self, *args, **kwargs):
        print(self.request.GET)
        return {'band_request': self.kwargs['pk'], 'censor': self.request.user.profile}
    
    def get_context_data(self, **kwargs):
        context = super(CensorVoteCreate, self).get_context_data(**kwargs)
        context['voted'] = CensorVote.objects.filter(censor=self.request.user.profile, band_request=self.kwargs['pk'])
        context['current_request'] = BandRequest.objects.get(pk=self.kwargs['pk'])
        return context

# The final voting system for censors
class BandRequestUpdate(GroupRequiredMixin, UpdateView):

    group_required = ['admin', 'Censor']

    model = BandRequest
    template_name = 'festival/verdict.html'
    fields = ['status', 'timeslot']
    success_url = reverse_lazy('festival:home')

    def get_initial(self, *args, **kwargs):
        return {'status': self.kwargs['decision'],}

    def form_valid(self, form):
        if form.cleaned_data['status'] == 1:
            reserved_slot = ArenaTimeSlot.objects.filter(id=form.cleaned_data['timeslot'].id)[0]
            if reserved_slot.reserved < reserved_slot.capacity:
                reserved_slot.reserved += 1
                reserved_slot.save()
            else:
                messages.add_message(self.request, messages.ERROR, 'The Arena\'s timeslots are full. Select a new timeslot or reject')
                return HttpResponseRedirect(reverse_lazy('festival:decision', kwargs={'pk':self.kwargs['pk'], 'decision': self.kwargs['decision']}))
            
        return super(BandRequestUpdate, self).form_valid(form)

gu-festival/festival/templates/base.html
{% load static %}
<html>
  <head>
    <title>
    {% block title %}
    
    {% endblock %}
    </title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'festival/style.css' %}">
  <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  {% block extra_head %}

  {% endblock %}

  </head>

  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'festival:home' %}">Home</a>
      </li>
      {% if user.groups.values.0.id == 1 or user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'festival:requests' %}">Requests</a>
      </li>
      {% endif %}
      
      {% if user.groups.values.0.id == 2 or user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'festival:band-request' %}">Send Request</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'festival:request-status' %}">My Request Status</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'festival:schedule' %}">Schedule</a>
      </li>
      <li class="nav-item login-logout">
        <a class="nav-link" 
        {% if user.is_authenticated %}
          href="{% url 'user_management:logout' %}">Logout
        {% else %}
          href="{% url 'user_management:login' %}">Login
        {% endif %}
        </a>
      </li>
    </ul>
    </div>
  </nav>
</header>

<body>

{% block content %}
      
{% endblock %}

<script>

const activeLink = document.URL
const links = document.querySelectorAll('.nav-link')
for (link of links) {
  if (link.href === activeLink) {
    link.classList.add('active')
  }
}
</script>

</body>

</html>