gu-festival/festival/urls.py
from django.urls import path
from .views import *

app_name = 'festival'
urlpatterns = [
    path('', index, name='home'),
    path('schedule/', ArenaList.as_view(), name='schedule'),
    path('request/', BandRequestPost.as_view(), name='band-request'),
    path('request/status/', BandRequestStatus.as_view(), name='request-status'),
    path('requests', BandRequestList.as_view(), name='requests'),
    # path('vote/', band_request_update, name='vote'),
    # path('requests/<int:pk>', BandRequestDetail.as_view(), name='request-detail'),
    path('requests/<int:pk>', CensorVoteCreate.as_view(), name='vote'),
    path('request/<int:pk>/<int:decision>', BandRequestUpdate.as_view(), name='decision'),
]

gu-festival/glukhie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('festival.urls')),
    path('account/', include('user_management.urls')),
    path('account/', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
]

gu-festival/festival/models.py
from django.db import models
from user_management.models import UserProfile


# Arena Model, complete
class Arena(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name
    

# ArenaTimeSlot model, complete
class ArenaTimeSlot(models.Model):
    NOON = 1
    DUSK = 2
    EVENING = 3

    TIME_CHOICES = [
        (NOON, "День"),
        (DUSK, "Ранний вечер"),
        (EVENING, "Поздний вечер"),
    ]
    
    arena = models.ForeignKey(Arena, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.IntegerField(choices=TIME_CHOICES, default=None)
    capacity = models.SmallIntegerField(default=0)
    reserved = models.SmallIntegerField(default=0)

    def __str__(self):
        return f"{self.arena} - {self.get_time_display()} - {self.date}"
    

# Band request model, complete
class BandRequest(models.Model):
    PASSED = 1
    REJECTED = 2
    IN_PROGRESS = 3

    STATUS = [
        (PASSED, 'Passed'),
        (REJECTED, 'Rejected'),
        (IN_PROGRESS, 'In progress'),
    ]

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    band_name = models.CharField(max_length=255)
    request_text = models.TextField()
    timeslot = models.ForeignKey(ArenaTimeSlot, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=IN_PROGRESS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Request by {self.band_name}"
    

# Censor vote model, complete
class CensorVote(models.Model):
    PASS = 1
    REJECT = 2

    VOTES = [
        (PASS, 'Pass'),
        (REJECT, 'Reject'),
        (None, 'None'),
    ]

    censor = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    band_request = models.ForeignKey(BandRequest, on_delete=models.CASCADE)
    vote = models.IntegerField(choices=VOTES, default=None)

gu-festival/festival/forms.py
from django import forms
from .models import BandRequest, CensorVote


class BandRequestForm(forms.ModelForm):
    class Meta:
        model = BandRequest
        fields = ('band_name', 'request_text', 'timeslot')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['band_name'].widget.attrs.update({'class':'form-control'})
        self.fields['request_text'].widget.attrs.update({'class':'form-control'})
        self.fields['timeslot'].widget.attrs.update({'class':'form-control'})


class CensorVoteForm(forms.ModelForm):

    class Meta(object):
        model = CensorVote
        fields = '__all__'
        widgets = {
            'band_request': forms.HiddenInput(),
            'censor': forms.HiddenInput(),
            'vote': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

gu-festival/festival/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Arena, ArenaTimeSlot
from django.views.generic import ListView, CreateView, DetailView, UpdateView, CreateView
from .forms import BandRequestForm, CensorVoteForm
from .models import BandRequest, CensorVote
from user_management.models import UserProfile
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from .mixins import GroupRequiredMixin
from django.views.generic import View
import datetime

# Homepage view, no functionality
def index(request):
    return render(request, 'festival/home.html')
    
# List all the Arenas and available ArenaTimeSlots
class ArenaList(ListView):
    context_object_name = 'arena_list'

    def get_queryset(self):
        return Arena.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ArenaList, self).get_context_data(**kwargs)
        context['arena_timeslot_first'] = ArenaTimeSlot.objects.filter(date=datetime.date(2020,1,30))
        context['arena_timeslot_second'] = ArenaTimeSlot.objects.filter(date=datetime.date(2020,1,31))
        context['bands'] = BandRequest.objects.filter(status=1)
        print(context['arena_timeslot_first'])
        print(context['arena_timeslot_second'])
        return context

# Handling the form for new band requests
class BandRequestPost(SuccessMessageMixin, GroupRequiredMixin, CreateView):

    group_required= ['admin', 'Censor', 'Musician']

    model = BandRequest
    form_class = BandRequestForm
    success_url = reverse_lazy('festival:home')
    template_name = 'festival/band_request.html'

    def form_valid(self, form):
        user = UserProfile.objects.get(user=self.request.user)
        form.instance.user = user
        return super(BandRequestPost, self).form_valid(form)

# Showing the status of the particular BandRequest (for Musicians)
class BandRequestStatus(GroupRequiredMixin, ListView):

    group_required = ['admin', 'Censor', 'Musician']

    model = BandRequest
    template_name = 'festival/user_request.html'
    context_object_name = 'bandrequest'
    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.get(user=self.request.user)
            return BandRequest.objects.filter(user=profile)
        else:
            return BandRequest.objects.none()

# Listing of all pending, approved and rejected BandRequests (for Censors)
class BandRequestList(GroupRequiredMixin, ListView):

    group_required = ['admin', 'Censor']

    model = BandRequest
    context_object_name = 'bandrequests'
    template_name = 'festival/requests.html'

    def get_context_data(self, *args, **kwargs):
        context = super(BandRequestList, self).get_context_data(*args, **kwargs)

        band_votes = {}

        # Very ugly method for getting the dictionary of BandRequest objects and calculated value of censor votes
        # NEEDS REVIEWING
        for i in BandRequest.objects.all():
            votes = 0
            for j in CensorVote.objects.all():
                if j.band_request == i:
                    if j.vote == 1:
                        votes += 1
                    elif j.vote == 2:
                        votes -= 2
            band_votes[i] = votes

        context['votes'] = band_votes
        print(context['votes'])
        return context
 
# Giving a censor an opportunity to accept or reject the pending request
class CensorVoteCreate(GroupRequiredMixin, CreateView):

    group_required = ['admin', 'Censor']

    model = CensorVote
    template_name = 'festival/vote.html'
    form_class = CensorVoteForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('festival:home')
    
    def get_initial(self, *args, **kwargs):
        print(self.request.GET)
        return {'band_request': self.kwargs['pk'], 'censor': self.request.user.profile}
    
    def get_context_data(self, **kwargs):
        context = super(CensorVoteCreate, self).get_context_data(**kwargs)
        context['voted'] = CensorVote.objects.filter(censor=self.request.user.profile, band_request=self.kwargs['pk'])
        context['current_request'] = BandRequest.objects.get(pk=self.kwargs['pk'])
        return context

# The final voting system for censors
class BandRequestUpdate(GroupRequiredMixin, UpdateView):

    group_required = ['admin', 'Censor']

    model = BandRequest
    template_name = 'festival/verdict.html'
    fields = ['status', 'timeslot']
    success_url = reverse_lazy('festival:home')

    def get_initial(self, *args, **kwargs):
        return {'status': self.kwargs['decision'],}

    def form_valid(self, form):
        if form.cleaned_data['status'] == 1:
            reserved_slot = ArenaTimeSlot.objects.filter(id=form.cleaned_data['timeslot'].id)[0]
            if reserved_slot.reserved < reserved_slot.capacity:
                reserved_slot.reserved += 1
                reserved_slot.save()
            else:
                messages.add_message(self.request, messages.ERROR, 'The Arena\'s timeslots are full. Select a new timeslot or reject')
                return HttpResponseRedirect(reverse_lazy('festival:decision', kwargs={'pk':self.kwargs['pk'], 'decision': self.kwargs['decision']}))
            
        return super(BandRequestUpdate, self).form_valid(form)

gu-festival/festival/templates/festival/arena_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'festival/schedule.css' %}">
{% endblock %}

{% block title %}
Schedule
{% endblock %}

{% block content %}

<div class="container">
{% for arena in arena_list %}
    <div class="arena">
    <h3 class="display-4">{{ arena.name }}</h3>

    <div class="timeslots">
    
        <div class="date">
        <p class="date-head">30 ЯНВАРЯ</p>
        {% for timeslot in arena_timeslot_first %}
            {% if timeslot.arena == arena %}
                <div class="timeslot">
                <h2>{{ timeslot.get_time_display }}</h2>
                    {% if user.groups.values.0.id == 1 or user.is_staff %}
                        <div class="alert alert-info" role="alert">
                            <li>Слотов: {{ timeslot.capacity }}</li>
                            <li>Зарезервировано: {{ timeslot.reserved }}</li>
                        </div>
                    {% endif %}
                    <div class="bands">
                    {% if timeslot.reserved != 0 %}
                        {% for band in bands %}
                            {% if band.timeslot == timeslot %}
                                <div class="band">{{ band.band_name }}</div>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <p>No performers</p>
                    {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
        <div class="date">
        <p class="date-head">31 ЯНВАРЯ</p>
        {% for timeslot in arena_timeslot_second %}
            {% if timeslot.arena == arena %}
                <div class="timeslot">
                <h2>{{ timeslot.get_time_display }}</h2>
                    {% if user.groups.values.0.id == 1 or user.is_staff %}
                        <div class="alert alert-info" role="alert">
                            <li>Слотов: {{ timeslot.capacity }}</li>
                            <li>Зарезервировано: {{ timeslot.reserved }}</li>
                        </div>
                    {% endif %}
                    <div class="bands">
                    {% if timeslot.reserved != 0 %}
                        {% for band in bands %}
                            {% if band.timeslot == timeslot %}
                                <div class="band">{{ band.band_name }}</div>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <p>No performers</p>
                    {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
       
    </div>
    </div>
{% endfor %}
</div>
{% endblock %}

gu-festival/festival/templates/festival/band_request.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Request
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'festival/band_request.css' %}">
{% endblock %}

{% block content %}
<div class='container'>
<form method='post'>
{% csrf_token %}
{{ form.as_p }}
<button type='submit' class="btn btn-primary mb-2">Submit</button>
</form>
</div>
{% endblock %}

gu-festival/festival/templates/festival/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
  <link rel='stylesheet' href="{% static 'festival/home.css' %}">
{% endblock %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class='container'>
  <img id="logo" src="{% static 'festival/img/logo.png' %}">
    <h1 class="display-4">
    {% if user.is_authenticated %}
    Hello, {{ user }}! 
    {% endif %}
    Welcome</h1>
    <p class="lead">{% lorem 1 %}</p>
    <hr class="my-4">
    <p>Please use the navbar above to navigate through this humble website</p>
  </div>
</div>
{% endblock %}

gu-festival/festival/templates/festival/requests.html
{% extends 'base.html' %}

{% load get_item %}
{% load static %}

{% block extra_head %}
<style>
  .album {
    background-color: rgba(255,255,255,0.7) !important;
  }
  .card-container {
    flex-direction: column;
    justify-content: space-around;
  }
  .card-title {
    font-size: 20px;
  }
  .btn-group a {
    margin: 10px;
  }
</style>
{% endblock %}

{% block title %}
VSE ZAPROSI
{% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
     <div class="row">
     {% for bandreq in bandrequests %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
            <rect width="100%" height="100%" fill="#f2f2f2"/>
            <image href="{% static 'festival/img/bg.png' %}" height="100%" width="100%" ></svg>
            <div class="card-body">
              <div class="card-container d-flex justify-content-between align-items-center">
                <div class="card-title">
                {{ bandreq }}
                </div>
                <div class="btn-group">
                  <a href='{% url 'festival:vote' bandreq.id %}'><button type="button" class="btn btn-sm btn-outline-primary">Vote</button></a>

                  {% if votes|get_item:bandreq > 2 %}
                  <a href='{% url 'festival:decision' bandreq.id 1 %}'><button type="button" class="btn btn-sm btn-outline-success" data-value="1">Accept</button></a>
                  {% endif %}
                  
                  <a href='{% url 'festival:decision' bandreq.id 2 %}'><button type="button" class="btn btn-sm btn-outline-danger" data-value="2">Reject</button></a>
                </div>
                <div class="btn-group">
                </div>
                <small class="text-muted">{{ bandreq.created_at }}</small>
               </div>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
</div>


{% endblock %}

gu-festival/festival/templates/festival/user_request.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'festival/request.css' %}">
{% endblock %}

{% block title %}
VASH REKVEST SIR
{% endblock %}

{% block content %}
<div class="container">

{% if bandrequest %}
    {% for breq in bandrequest %}
        <h1 class="display-4">{{ breq }}</h1>
        
        <div class="request">
        <p>Hello, <b>{{ user.profile.user }}</b>!</p>
        <p>Your band <b>{{ breq.band_name }}</b> has requested a slot on <b>{{ breq.timeslot }}</b></p>
        {% if breq.status == 3 %}
            <p class="alert alert-secondary" role="alert">Your request is currently in progress. Please, return later to see if your request has been accepted or rejected.</div>
        {% elif breq.status == 2 %}
            <p class="alert alert-danger" role="alert">Your request has been rejected.<p>
        {% else %}
            <p class="alert alert-success" role="alert">Your request has been approved. Contact our event administrator for further instructions.</p>      
        {% endif %}
    {% endfor %}
    </div>
{% else %}
    <div class="no-request">
        You posted no requests recently.
    </div>
{% endif %}
</div>
{% endblock %}

gu-festival/festival/templates/festival/verdict.html
{% extends 'base.html' %}

{% block title %}
???
{% endblock %}

{% block content %}
<ul class='messages'>
{% for message in messages %}
<li>{{ message }}</li>
{% endfor %}
</ul>


<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

gu-festival/festival/templates/festival/vote.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
<audio autoplay>
<source src="{% static 'festival/mp3/vote.mp3' %}" type="audio/mp3">
</audio>
<link rel="stylesheet" href="{% static 'festival/vote.css' %}">
{% endblock %}

{% block title %}
VASH REKVEST SIR
{% endblock %}

{% block content %}
<div class='container'>
<div class="card text-center">
  <div class="card-header">
    GOLOSOWANIE
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ object }}</h5>
    <p class="card-text">{{ object.request_text }}</p>
  </div>

  {% if not voted %}
  <section class='form-section'>
        <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.censor.errors }}
            <label for="{{ form.censor.id_for_label }}" class='col-sm-12 col-form-label'>
            <p class='h3'>Hi, {{ user.profile.user }}</p>
            </label>
            <div>
              {{ form.censor }}
            </div>
          </div>
          <div class="form-group row">
            {{ form.band_request.errors }}
            <label for="{{ form.band_request.id_for_label }}" class='col-sm-12 col-form-label'>
            <p class='h4'>Make decision for {{ current_request.band_name }}</p>
            </label>
            <div>
              {{ form.band_request }}
            </div>
          </div>
          <div class="form-group row verdict">
            {{ form.vote.errors }}
            <label for="{{ form.vote.id_for_label }}" class='col-sm-2 col-form-label'>
            Verdict:
            </label>
            <div class="col-sm-2">
              {{ form.vote }}
            </div>
          </div>

        <input type="submit" class="btn btn-primary" value="Save">
      </form>
  </section>
  {% else %}
  <p> You have already voted for this request. Your verdict: {{ voted.0.get_vote_display }}
  {% endif %}
</div>
</div>

{% endblock %}